version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t test_dir
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd test_dir
      - zip -r ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Test --zip-file fileb://deployment_package.zip
      - echo "DONE!!"